# Generated by Django 2.2 on 2020-11-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_setting_sologan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='flickr_url',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='googleplus_url',
        ),
        migrations.AddField(
            model_name='setting',
            name='whatsapp_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
